const TWILIO_STATUS_ACCEPTED = 'accepted';
const TWILIO_STATUS_SCHEDULED = 'scheduled';
const TWILIO_STATUS_QUEUED = 'queued';
const TWILIO_STATUS_SENDING = 'sending';
const TWILIO_STATUS_SENT = 'sent';
const TWILIO_STATUS_DELIVERED = 'delivered';
const TWILIO_STATUS_UNDELIVERED = 'undelivered';

const TWILIO_PENDING_STATUSES = [
    TWILIO_STATUS_ACCEPTED,
    TWILIO_STATUS_SCHEDULED,
    TWILIO_STATUS_QUEUED,
    TWILIO_STATUS_SENDING
];

const TWILIO_SUCCESSFUL_STATUSES = [
    TWILIO_STATUS_SENT,
    TWILIO_STATUS_DELIVERED
];

const TWILIO_FAILURE_STATUSES = [
    TWILIO_STATUS_UNDELIVERED
];

module.exports = {
    TWILIO_STATUS_ACCEPTED,
    TWILIO_STATUS_SCHEDULED,
    TWILIO_STATUS_QUEUED,
    TWILIO_STATUS_SENDING,
    TWILIO_STATUS_SENT,
    TWILIO_STATUS_DELIVERED,
    TWILIO_STATUS_UNDELIVERED,

    TWILIO_PENDING_STATUSES,
    TWILIO_SUCCESSFUL_STATUSES,
    TWILIO_FAILURE_STATUSES
};
